"""initial

Revision ID: db3ddf02da9c
Revises: 675864fb0f6f
Create Date: 2023-11-16 12:49:29.842884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3ddf02da9c'
down_revision: Union[str, None] = '675864fb0f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_thread_id', table_name='posts')
    op.drop_constraint('posts_thread_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thread_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_thread_id_fkey', 'posts', 'threads', ['thread_id'], ['id'])
    op.create_index('ix_posts_thread_id', 'posts', ['thread_id'], unique=False)
    # ### end Alembic commands ###
