"""revase

Revision ID: e0a9ee341ad3
Revises: 0668d8adb192
Create Date: 2023-11-16 13:23:21.000342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a9ee341ad3'
down_revision: Union[str, None] = '0668d8adb192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_posts_thread_id'), 'posts', ['thread_id'], unique=False)
    op.create_foreign_key(None, 'posts', 'threads', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_thread_id'), table_name='posts')
    op.drop_column('posts', 'thread_id')
    # ### end Alembic commands ###
